### ISSUE TITLE
selectionChanged handler lost controller's context

### ISSUE THREAD

**Issue by chfw** [zewa666/aurelia-jstree#1]
Hi

First of all, thanks for sharing your element. It does work. However, I found it difficult to pass on the controller's context into the `selectionChanged` handler.

My use case is:

```
export class Controller {

    def async selectionChanged(e, data){
          const data = await this.api.get(data['node']['original']['my_data_id']); // <-- api becomes undefined.
    }

}
```

I have forked and attempted to solve it but fail:

a) My alternative does not propagate the event to controller level
b) au-js-tree.html is not copied to /dist/native-module folder.

**Comment by zewa666** [comment]
Ups yeah my Docs are wrong and saying you should pass bind, where additionally the context would need to be bound. Alternatively the .call binding would solve that.

This plugin was rather a quick sample, i'll check it next week once back from vacation to update everything. Sorry for the troubles it gave you

**Comment by zewa666** [comment]
ok so in your example above the html where you use the jstree should be like this:

```html
<au-js-tree
    settings.bind="jstreeConfig"
    data.bind="data"
    selection-changed.bind="onSelectionChanged.bind($this)"
    node-moved.bind="onNodeMoved.bind($this)"></au-js-tree>
```

Notice that you've rebound the context to `$this` which points to the context of the vm itself.

Alternatively as described in the README you can pass a lambda expression as bound value vs a method name.
