### ISSUE TITLE
style css needs to imported

### ISSUE THREAD

**Issue by chfw** [zewa666/aurelia-jstree#2]
Hi

I found that I have to include the following statement so as to get the js-tree styled, right after `import 'aurelia-jstree'` in my `main.ts`:

`import 'jstree/themes/default/style.min.css';`

**Comment by zewa666** [comment]
Thats true, as mentioned in the other issue this plugin was a quickshot without proper Docs. Feel free to create a PR to update the readme. I'll be back next week and will give it some more love

**Comment by zewa666** [comment]
readme has been updated
